/* Generated by ledger-app/scripts/gen-fq-params.ts — DO NOT EDIT.
 * Source-of-truth: ./gen-fq-params.ts.
 *
 * BN254 BASE field constants (= Grumpkin SCALAR field). Distinct from
 * BN254 scalar field used by crypto/poseidon2/fr_params.h. */
#pragma once

#include "fq.h"

extern const gk_fq_t AZ_FQ_P;
extern const gk_fq_t AZ_FQ_R2;
extern const uint64_t AZ_FQ_MU;
