/* Generated by ledger-app/scripts/gen-fq-params.ts — DO NOT EDIT. */
#include "fq_params.h"

const gk_fq_t AZ_FQ_P = {{ 0x3c208c16d87cfd47ULL, 0x97816a916871ca8dULL, 0xb85045b68181585dULL, 0x30644e72e131a029ULL }};

const gk_fq_t AZ_FQ_R2 = {{ 0xf32cfc5b538afa89ULL, 0xb5e71911d44501fbULL, 0x47ab1eff0a417ff6ULL, 0x06d89f71cab8351fULL }};

const uint64_t AZ_FQ_MU = 0x87d20782e4866389ULL;
