/* Generated by gen-clear-signing-v0.ts. DO NOT EDIT.
 * Source-of-truth: packages/adapter-ledger/clear-signing-v0/manifest.json
 *
 * M7 P2: reviewed deploy profiles. NOT the same shape as CS_VERBS — verbs are
 * selector-matched runtime calls; profiles are deploy-time templates pinning
 * class id, constructor selector, fee path, and the rendering schema for the
 * on-device review screen.
 */
#pragma once
#include <stdint.h>

#define CS_DEPLOY_PROFILE_COUNT 2u

typedef enum {
    CS_DEPLOY_ARG_SCHEMA_ECDSA_K_PUBKEY_XY = 1,  /* [u8;32] x || [u8;32] y → 64 Frs */
    CS_DEPLOY_ARG_SCHEMA_SCHNORR_PUBKEY_XY = 2,  /* Field x || Field y → 2 Frs */
} cs_deploy_arg_schema_e;

typedef enum {
    CS_FEE_MODE_EXTERNAL = 0,
} cs_fee_mode_e;

typedef struct {
    uint8_t  account_class_id[32];     /* Fr BE */
    uint32_t ctor_selector_u32;        /* low-4-bytes selector */
    uint8_t  arg_schema;               /* cs_deploy_arg_schema_e */
    uint16_t ctor_arg_byte_len;        /* total bytes of ABI-encoded ctor args */
    uint8_t  deployer[32];             /* Fr BE; ZERO for universal */
    uint8_t  sponsor_fpc_address[32];  /* Fr BE */
    uint32_t sponsor_selector_u32;
    uint8_t  fee_mode;                 /* cs_fee_mode_e */
    uint8_t  _reserved[2];             /* pad */
} cs_deploy_profile_t;

extern const cs_deploy_profile_t CS_DEPLOY_PROFILES[CS_DEPLOY_PROFILE_COUNT];

/* Returns NULL if profile_index is out of range. */
const cs_deploy_profile_t *cs_deploy_profile_lookup(uint8_t profile_index);
