/* Generated by gen-clear-signing-v0.ts. DO NOT EDIT.
 * Source-of-truth: packages/adapter-ledger/clear-signing-v0/manifest.json
 * aztec-packages pin: 2770bcb82d40323060c2f9c71aaf293b640efbef
 * aztec-standards pin: @defi-wonderland/aztec-standards@4.2.0-aztecnr-rc.2
 */
#pragma once
#include <stdint.h>

#define CS_REGISTRY_SLOTS 5u
#define CS_SYMBOL_LEN 8u

typedef enum {
    CS_KIND_EMPTY = 0,
    CS_KIND_TOKEN = 1,
    CS_KIND_SPONSOR = 2,
} cs_contract_kind_e;

typedef struct {
    uint8_t  kind;                /* cs_contract_kind_e */
    uint8_t  address[32];         /* AztecAddress, 32 BE bytes */
    char     symbol[CS_SYMBOL_LEN]; /* null-padded */
    uint8_t  decimals;
    uint8_t  _reserved[3];        /* pad to 44B; alignment */
} cs_registry_entry_t;

extern const cs_registry_entry_t CS_REGISTRY[CS_REGISTRY_SLOTS];

/* Returns matching entry pointer (kind != EMPTY) or NULL. */
const cs_registry_entry_t *cs_registry_lookup(const uint8_t target[32]);
