/* Generated by gen-clear-signing-v0.ts. DO NOT EDIT.
 *
 * M7 P2: reviewed deploy profiles. Cross-checked at codegen against the live
 * EcdsaKAccountContractArtifact — fail-closed on class-id or ctor-selector drift.
 */

export type CsDeployProfileId = 'DEPLOY_ACCOUNT_ECDSAK_V1';

export interface CsDeployProfile {
  readonly id: CsDeployProfileId;
  readonly profile_index: number;
  readonly version: number;
  readonly account_class_id: string;
  readonly ctor_selector_u32: number;
  readonly ctor_arg_schema: 'ecdsa_k_pubkey_xy';
  readonly ctor_arg_byte_len: number;
  readonly deployer: string;
  readonly sponsor_fpc_address: string;
  readonly sponsor_selector_u32: number;
  readonly fee_mode: 'EXTERNAL';
  readonly display_name: string;
}

export const CS_DEPLOY_PROFILES: readonly CsDeployProfile[] = [
  {
    id: 'DEPLOY_ACCOUNT_ECDSAK_V1',
    profile_index: 0,
    version: 1,
    account_class_id: '0x1850bf05edce02839f8f95c164b10b7a8f82177ae7921a2bc2c083ceece76327',
    ctor_selector_u32: 0xb6b8e0f8,
    ctor_arg_schema: 'ecdsa_k_pubkey_xy',
    ctor_arg_byte_len: 64,
    deployer: '0x0000000000000000000000000000000000000000000000000000000000000000',
    sponsor_fpc_address: '0x254082b62f9108d044b8998f212bb145619d91bfcd049461d74babb840181257',
    sponsor_selector_u32: 0x23d77f89,
    fee_mode: 'EXTERNAL',
    display_name: 'EcdsaKAccount v1',
  },
] as const;

export function csDeployProfileLookup(id: CsDeployProfileId): CsDeployProfile | undefined {
  return CS_DEPLOY_PROFILES.find((p) => p.id === id);
}
