/* Generated by gen-clear-signing-v0.ts. DO NOT EDIT.
 * Single source of truth: clear-signing-v0/manifest.json
 */

export type CsContractKind = 'EMPTY' | 'TOKEN' | 'SPONSOR';

export interface CsRegistryEntry {
  readonly kind: CsContractKind;
  readonly address: string;
  readonly symbol: string;
  readonly decimals: number;
}

export const CS_REGISTRY: readonly CsRegistryEntry[] = [
  /* slot 0 */ {
    kind: 'TOKEN',
    address: '0x2af7c3bdd0bee3d825ec40786dc479bfd85f749b45da78a20ddca8ec3e4347c5',
    symbol: 'USDC',
    decimals: 6,
  },
  /* slot 1 */ {
    kind: 'TOKEN',
    address: '0x060e0d2735b8e7d39fabe8c02b46535b33a7d4e685fa7e31e833b2edfdc26224',
    symbol: 'ETH',
    decimals: 18,
  },
  /* slot 2 */ {
    kind: 'SPONSOR',
    address: '0x254082b62f9108d044b8998f212bb145619d91bfcd049461d74babb840181257',
    symbol: 'FPC',
    decimals: 0,
  },
  /* slot 3 */ {
    kind: 'EMPTY',
    address: '0x0000000000000000000000000000000000000000000000000000000000000000',
    symbol: '',
    decimals: 0,
  },
  /* slot 4 */ {
    kind: 'EMPTY',
    address: '0x0000000000000000000000000000000000000000000000000000000000000000',
    symbol: '',
    decimals: 0,
  },
] as const;

export function csRegistryLookup(addressHex: string): CsRegistryEntry | undefined {
  const normalized = addressHex.toLowerCase().startsWith('0x')
    ? addressHex.toLowerCase()
    : '0x' + addressHex.toLowerCase();
  return CS_REGISTRY.find((e) => e.kind !== 'EMPTY' && e.address.toLowerCase() === normalized);
}
