/* Generated by gen-clear-signing-v0.ts. DO NOT EDIT. */

export type CsVerb =
  | 'TRANSFER_PRIV_PUB'
  | 'TRANSFER_PRIV_PRIV'
  | 'TRANSFER_PUB_PRIV'
  | 'TRANSFER_PUB_PUB'
  | 'MINT_PUB'
  | 'MINT_PRIV'
  | 'SPONSOR';

export interface CsVerbEntry {
  readonly verb: CsVerb;
  readonly kind: 'TOKEN' | 'SPONSOR';
  readonly selector_u32: number;
  readonly is_public: boolean;
  readonly wire_arg_count: number;
  readonly display_name: string;
  readonly args: readonly string[];
}

export const CS_VERBS: readonly CsVerbEntry[] = [
  {
    verb: 'TRANSFER_PRIV_PUB',
    kind: 'TOKEN',
    selector_u32: 0xd4fcf9f6,
    is_public: false,
    wire_arg_count: 4,
    display_name: 'Transfer priv→pub',
    args: ['from', 'to', 'amount', 'nonce'],
  },
  {
    verb: 'TRANSFER_PRIV_PRIV',
    kind: 'TOKEN',
    selector_u32: 0xfe438afc,
    is_public: false,
    wire_arg_count: 4,
    display_name: 'Transfer priv→priv',
    args: ['from', 'to', 'amount', 'nonce'],
  },
  {
    verb: 'TRANSFER_PUB_PRIV',
    kind: 'TOKEN',
    selector_u32: 0x0c3d0a8e,
    is_public: false,
    wire_arg_count: 4,
    display_name: 'Transfer pub→priv',
    args: ['from', 'to', 'amount', 'nonce'],
  },
  {
    verb: 'TRANSFER_PUB_PUB',
    kind: 'TOKEN',
    selector_u32: 0xc47adea0,
    is_public: true,
    wire_arg_count: 4,
    display_name: 'Transfer pub→pub',
    args: ['from', 'to', 'amount', 'nonce'],
  },
  {
    verb: 'MINT_PUB',
    kind: 'TOKEN',
    selector_u32: 0x451b5fae,
    is_public: true,
    wire_arg_count: 2,
    display_name: 'Mint public',
    args: ['to', 'amount'],
  },
  {
    verb: 'MINT_PRIV',
    kind: 'TOKEN',
    selector_u32: 0x87f0f0a4,
    is_public: false,
    wire_arg_count: 2,
    display_name: 'Mint private',
    args: ['to', 'amount'],
  },
  {
    verb: 'SPONSOR',
    kind: 'SPONSOR',
    selector_u32: 0x23d77f89,
    is_public: false,
    wire_arg_count: 0,
    display_name: 'Sponsor fee (private)',
    args: [],
  },
] as const;

export function csVerbLookup(
  kind: 'TOKEN' | 'SPONSOR',
  selectorU32: number,
): CsVerbEntry | undefined {
  return CS_VERBS.find((v) => v.kind === kind && v.selector_u32 === selectorU32);
}
