/**
 * Host-parity test for the device-side Poseidon2 implementation.
 *
 * Builds `ledger-app/tests/poseidon2_host/poseidon2_cli` (which compiles the
 * SAME C sources that ship in the Ledger app: `src/crypto/poseidon2/*.c`) and
 * checks every golden-vector hash matches barretenberg/Aztec.
 *
 * Vectors come from `ledger-app/tests/golden_vectors/l4_outer_hashes.json`,
 * generated by `packages/adapter-ledger/scripts/gen-l4-vectors.ts`.
 *
 * If this passes locally + on CI, the device implementation is mathematically
 * compatible with Aztec — L4 finalize_and_sign can re-derive outer_hash on
 * device and compare with what the host claims.
 */
import { afterAll, beforeAll, describe, expect, test } from 'bun:test';
import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const HOST_DIR = join(__dirname, '../../..', 'ledger-app', 'tests', 'poseidon2_host');
const CLI = join(HOST_DIR, 'poseidon2_cli');
const VECTORS_PATH = join(
  __dirname,
  '../../..',
  'ledger-app',
  'tests',
  'golden_vectors',
  'l4_outer_hashes.json',
);

interface VectorCall {
  args_hash_hex: string;
  function_selector_hex: string;
  target_address_hex: string;
  is_public: boolean;
  hide_msg_sender: boolean;
  is_static: boolean;
}

interface ScenarioInputs {
  consumer_hex: string;
  chain_id_hex: string;
  protocol_version_hex: string;
  tx_nonce_hex: string;
  real_calls: VectorCall[];
}

interface Scenario {
  name: string;
  description: string;
  inputs: ScenarioInputs;
  expected: { inner_hash_hex: string; outer_hash_hex: string };
}

interface VectorsFile {
  _meta: {
    aztec_packages_commit: string;
    app_max_calls: number;
    domain_separators: {
      SIGNATURE_PAYLOAD: number;
      AUTHWIT_OUTER: number;
      PUBLIC_CALLDATA: number;
    };
    canonical_padding_call: VectorCall;
    poseidon2_separator_smoke: {
      zero_hex: string;
      one_hex: string;
      domain_zero_hex: string;
      domain_sigpayload_zero_hex: string;
    };
  };
  scenarios: Scenario[];
}

const vectors = JSON.parse(readFileSync(VECTORS_PATH, 'utf-8')) as VectorsFile;
const APP_MAX_CALLS = vectors._meta.app_max_calls;

function buildCli(): void {
  const res = spawnSync('make', [], { cwd: HOST_DIR, encoding: 'utf-8' });
  if (res.status !== 0) {
    throw new Error(
      `make failed (status ${res.status}):\nstdout: ${res.stdout}\nstderr: ${res.stderr}`,
    );
  }
}

function runCli(args: string[]): string[] {
  const res = spawnSync(CLI, args, { encoding: 'utf-8' });
  if (res.status !== 0) {
    throw new Error(
      `cli failed (status ${res.status}) for args [${args.join(' ')}]:\nstderr: ${res.stderr}`,
    );
  }
  return res.stdout.trim().split('\n');
}

function boolToFieldHex(b: boolean): string {
  return `0x${'00'.repeat(31)}${b ? '01' : '00'}`;
}

function callFields(c: VectorCall): string[] {
  return [
    `0x${c.args_hash_hex}`,
    `0x${c.function_selector_hex}`,
    `0x${c.target_address_hex}`,
    boolToFieldHex(c.is_public),
    boolToFieldHex(c.hide_msg_sender),
    boolToFieldHex(c.is_static),
  ];
}

function innerHashInput(scenario: Scenario): string[] {
  const padded: VectorCall[] = [...scenario.inputs.real_calls];
  while (padded.length < APP_MAX_CALLS) {
    padded.push(vectors._meta.canonical_padding_call);
  }
  const fields: string[] = [];
  for (const c of padded) fields.push(...callFields(c));
  fields.push(`0x${scenario.inputs.tx_nonce_hex}`);
  return fields;
}

beforeAll(() => {
  if (!existsSync(CLI)) buildCli();
});

afterAll(() => {
  /* leave the CLI binary in place — useful for ad-hoc debugging. */
});

describe('Poseidon2 host parity', () => {
  test('raw permutation smoke', () => {
    const res = spawnSync(CLI, ['smoke'], { encoding: 'utf-8' });
    expect(res.status).toBe(0);
    expect(res.stdout.trim()).toBe('smoke OK');
  });

  describe('separator_smoke', () => {
    const sm = vectors._meta.poseidon2_separator_smoke;

    test('poseidon2Hash([]) — sponge with no inputs', () => {
      expect(runCli(['hash'])[0]).toBe(sm.zero_hex);
    });

    test('poseidon2Hash([Fr(1)]) — single field absorb', () => {
      const one = `0x${'00'.repeat(31)}01`;
      expect(runCli(['hash', one])[0]).toBe(sm.one_hex);
    });

    test('poseidon2HashWithSeparator([], 0)', () => {
      expect(runCli(['hash-sep', '0'])[0]).toBe(sm.domain_zero_hex);
    });

    test('poseidon2HashWithSeparator([], SIGNATURE_PAYLOAD)', () => {
      expect(
        runCli(['hash-sep', String(vectors._meta.domain_separators.SIGNATURE_PAYLOAD)])[0],
      ).toBe(sm.domain_sigpayload_zero_hex);
    });
  });

  describe('canonical padding args_hash', () => {
    test('computeCalldataHash([0]) — padding call args_hash', () => {
      const [got] = runCli([
        'hash-sep',
        String(vectors._meta.domain_separators.PUBLIC_CALLDATA),
        `0x${'00'.repeat(32)}`,
      ]);
      expect(got).toBe(vectors._meta.canonical_padding_call.args_hash_hex);
    });
  });

  describe.each(vectors.scenarios)('scenario %#: $name', (scenario) => {
    test(`${scenario.name}: inner_hash`, () => {
      const fields = innerHashInput(scenario);
      const [got] = runCli([
        'hash-sep',
        String(vectors._meta.domain_separators.SIGNATURE_PAYLOAD),
        ...fields,
      ]);
      expect(got).toBe(scenario.expected.inner_hash_hex);
    });

    test(`${scenario.name}: outer_hash`, () => {
      const [got] = runCli([
        'hash-sep',
        String(vectors._meta.domain_separators.AUTHWIT_OUTER),
        `0x${scenario.inputs.consumer_hex}`,
        `0x${scenario.inputs.chain_id_hex}`,
        `0x${scenario.inputs.protocol_version_hex}`,
        `0x${scenario.expected.inner_hash_hex}`,
      ]);
      expect(got).toBe(scenario.expected.outer_hash_hex);
    });
  });
});
