/**
 * M8 Phase 2 — Codegen for `ledger-app/src/crypto/grumpkin/fq_params.{c,h}`.
 *
 * Computes BN254 BASE field (= Grumpkin SCALAR field) Montgomery constants
 * and emits them in 4×u64 little-endian limb form. Distinct prime from
 * Aztec `Fr` (the BN254 scalar field that lives in `crypto/poseidon2/fr.c`).
 *
 *   p_fq  = 0x30644e72e131a029b85045b68181585d97816a916871ca8d3c208c16d87cfd47
 *   R     = 2^256
 *   R²    = R * R mod p_fq        (used by fq_from_bytes_be to enter
 *                                   Montgomery form via one mul)
 *   µ     = (-p_fq⁻¹) mod 2^64    (low 64 bits of -p⁻¹; CIOS reduction
 *                                   multiplier)
 *
 * Codex final-audit MAJOR #1 deliverable: this file is the proof-of-distinctness
 * that the Grumpkin scalar field is NOT the same as Aztec `Fr` and therefore
 * cannot alias `fr_t` from poseidon2. Re-running this script regenerates the
 * .c/.h with the same bytes.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const P_FQ = 0x30644e72e131a029b85045b68181585d97816a916871ca8d3c208c16d87cfd47n;
const R = 1n << 256n;
const R2 = (R * R) % P_FQ;
const MOD_2_64 = 1n << 64n;

function modInverse(a: bigint, mod: bigint): bigint {
  let [oldR, r] = [a, mod];
  let [oldS, s] = [1n, 0n];
  while (r !== 0n) {
    const q = oldR / r;
    [oldR, r] = [r, oldR - q * r];
    [oldS, s] = [s, oldS - q * s];
  }
  return ((oldS % mod) + mod) % mod;
}

const P_INV_LOW = modInverse(P_FQ % MOD_2_64, MOD_2_64);
const MU = (MOD_2_64 - P_INV_LOW) % MOD_2_64;

/** Decompose a BigInt into 4 × u64 little-endian limbs. */
function toLimbs(x: bigint): bigint[] {
  return [0, 1, 2, 3].map((i) => (x >> BigInt(i * 64)) & 0xffffffffffffffffn);
}

function hexLimb(l: bigint): string {
  return `0x${l.toString(16).padStart(16, '0')}ULL`;
}

const pLimbs = toLimbs(P_FQ);
const r2Limbs = toLimbs(R2);

const headerOut = `/* Generated by ledger-app/scripts/gen-fq-params.ts — DO NOT EDIT.
 * Source-of-truth: ./gen-fq-params.ts.
 *
 * BN254 BASE field constants (= Grumpkin SCALAR field). Distinct from
 * BN254 scalar field used by crypto/poseidon2/fr_params.h. */
#pragma once

#include "fq.h"

extern const gk_fq_t AZ_FQ_P;
extern const gk_fq_t AZ_FQ_R2;
extern const uint64_t AZ_FQ_MU;
`;

const sourceOut = `/* Generated by ledger-app/scripts/gen-fq-params.ts — DO NOT EDIT. */
#include "fq_params.h"

const gk_fq_t AZ_FQ_P = {{ ${pLimbs.map(hexLimb).join(', ')} }};

const gk_fq_t AZ_FQ_R2 = {{ ${r2Limbs.map(hexLimb).join(', ')} }};

const uint64_t AZ_FQ_MU = ${hexLimb(MU)};
`;

const headerPath = fileURLToPath(new URL('../src/crypto/grumpkin/fq_params.h', import.meta.url));
const sourcePath = fileURLToPath(new URL('../src/crypto/grumpkin/fq_params.c', import.meta.url));
writeFileSync(headerPath, headerOut);
writeFileSync(sourcePath, sourceOut);
console.log(`Wrote ${headerPath}`);
console.log(`Wrote ${sourcePath}`);
console.log(`p_fq    = 0x${P_FQ.toString(16)}`);
console.log(`R² mod p= 0x${R2.toString(16)}`);
console.log(`µ       = 0x${MU.toString(16)}`);
